#!/usr/bin/env bash
# demoflow.sh
#
# Narrates the full demo flow on the command line — use this as a presenter
# reference during the demo or to walk a colleague through what will happen.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Read report URL from infra.yml if available
REPORT_URL=""
if [ -f "$SCRIPT_DIR/ansible/vars/infra.yml" ]; then
  REPORT_URL=$(grep 'report_url:' "$SCRIPT_DIR/ansible/vars/infra.yml" | awk '{print $2}' | tr -d '"')
fi
REPORT_URL="${REPORT_URL:-https://<report_server_ip>/failover_report.html}"

clear
echo ""
echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║      Red Hat Summit 2026 — NetBox Circuit Failover Demo                 ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "  The Scenario"
echo "  ─────────────"
echo "  A global enterprise runs WAN circuits between GB-Bristol (UK hub) and"
echo "  US-Atlanta (regional office). The primary IPLC circuit fails. Instead"
echo "  of a frantic manual response, the entire failover — router config,"
echo "  CMDB update, and incident report — happens automatically in seconds."
echo ""
read -r -p "  Press ENTER to begin the demo walkthrough..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  STEP 1 — Set the scene"
echo "  ─────────────────────"
echo ""
echo "  Open NetBox Visual Explorer:"
echo "    https://app.netboxlabs.com/visual-explorer"
echo ""
echo "  ▶ Show the live topology map. All circuits are ACTIVE."
echo "    Two IPLC circuits connect GB-Bristol to US-Atlanta:"
echo "      • IPLC-GB-AT-PRI  (primary, active)"
echo "      • IPLC-GB-AT-SEC  (backup, offline — not yet in use)"
echo ""
echo "  Key message: NetBox is the real-time source of truth."
echo "               The map reflects live circuit state."
echo ""
read -r -p "  Press ENTER for Step 2..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  STEP 2 — Trigger the failure"
echo "  ─────────────────────────────"
echo ""
echo "  Open NetBox Copilot (the AI chat assistant) and say:"
echo ""
echo "    ┌───────────────────────────────────────────────────────────┐"
echo "    │  \"IPLC-GB-AT-PRI has failed — set it to offline\"          │"
echo "    └───────────────────────────────────────────────────────────┘"
echo ""
echo "  ▶ Copilot PATCHes IPLC-GB-AT-PRI status → offline via the NetBox API."
echo "  ▶ A NetBox event rule fires immediately and sends a webhook to EDA."
echo ""
echo "  Key message: One natural language instruction. No scripts, no tickets."
echo ""
read -r -p "  Press ENTER for Step 3..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  STEP 3 — Watch the automation"
echo "  ──────────────────────────────"
echo ""
echo "  Open AAP Controller:"
echo "    https://netbox-aap25.demoredhat.com"
echo ""
echo "  ▶ EDA receives the webhook on the event stream."
echo "  ▶ The rulebook triggers 'Circuit Failover Workflow' in AAP."
echo ""
echo "  Watch the workflow run — two parallel steps:"
echo ""
echo "    ┌─ Step 1: Circuit Failover (pb_circuit_failover.yml) ──────────────┐"
echo "    │  • Queries NetBox for IPLC-GB-AT-PRI and its A/Z sites           │"
echo "    │  • Discovers all dd-tagged backup circuits between the same sites │"
echo "    │  • Selects IPLC-GB-AT-SEC (highest committed bandwidth)           │"
echo "    │  • SSHs into gb-brs-rtr-01 (Cisco C8000V, eu-west-2)             │"
echo "    │    → no ip route 0.0.0.0 0.0.0.0 172.16.0.1                     │"
echo "    │    → ip route 0.0.0.0 0.0.0.0 172.16.1.1                        │"
echo "    │  • PATCHes NetBox: IPLC-GB-AT-PRI → offline, SEC → active        │"
echo "    └────────────────────────────────────────────────────────────────────┘"
echo "                              ↓ on success"
echo "    ┌─ Step 2: Deploy Report (pb_deploy_report.yml) ──────────────────┐"
echo "    │  • Re-queries NetBox for current circuit state                  │"
echo "    │  • Generates HTML incident report (Jinja2 template)             │"
echo "    │  • Deploys report to the report web server over SSH             │"
echo "    └──────────────────────────────────────────────────────────────────┘"
echo ""
echo "  Key message: Real devices. Real config. AAP is the automation engine."
echo "               EDA is the event-driven trigger — zero human polling."
echo ""
read -r -p "  Press ENTER for Step 4..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  STEP 4 — Watch the map update"
echo "  ──────────────────────────────"
echo ""
echo "  Return to NetBox Visual Explorer."
echo ""
echo "  ▶ Refresh the page."
echo "  ▶ IPLC-GB-AT-PRI has DISAPPEARED from the map (it's offline)."
echo "  ▶ IPLC-GB-AT-SEC is now shown as ACTIVE — the backup is in use."
echo ""
echo "  Key message: NetBox reflects the new topology immediately."
echo "               No manual CMDB update. AAP wrote the changes back."
echo ""
read -r -p "  Press ENTER for Step 5..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  STEP 5 — Open the incident report"
echo "  ───────────────────────────────────"
echo ""
echo "  Open the auto-generated report:"
echo "    $REPORT_URL"
echo ""
echo "  ▶ The report shows:"
echo "    • Which circuit failed (IPLC-GB-AT-PRI)"
echo "    • Which backup was activated (IPLC-GB-AT-SEC)"
echo "    • Committed bandwidth comparison"
echo "    • Router config changes applied"
echo "    • Timestamps and automation steps"
echo ""
echo "  Key message: Instant audit trail. No one had to write this."
echo ""
read -r -p "  Press ENTER for Step 6..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  STEP 6 — Confirm with Claude via MCP"
echo "  ──────────────────────────────────────"
echo ""
echo "  Ask Claude (in Claude Code, connected to NetBox MCP):"
echo ""
echo "    ┌────────────────────────────────────────────────────────────────────┐"
echo "    │  \"What is the current status of IPLC-GB-AT-PRI?\"                  │"
echo "    │  \"Which circuit is now active between GB-Bristol and US-Atlanta?\" │"
echo "    └────────────────────────────────────────────────────────────────────┘"
echo ""
echo "  ▶ Claude queries NetBox through the MCP server."
echo "  ▶ Returns: IPLC-GB-AT-PRI is offline. IPLC-GB-AT-SEC is active."
echo "  ▶ No UI. No dashboard. Direct structured data from the source of truth."
echo ""
echo "  Key message: NetBox as an AI-accessible API. Claude as the last mile."
echo ""
read -r -p "  Press ENTER to see the reset instructions..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  RESET (between demo runs)"
echo "  ──────────────────────────"
echo ""
echo "  Run:  ./reset.sh"
echo ""
echo "  This will:"
echo "    ✓ Set IPLC-GB-AT-PRI back to active"
echo "    ✓ Set IPLC-GB-AT-SEC back to offline"
echo "    ✓ Restore primary default route on gb-brs-rtr-01 (172.16.0.1)"
echo "    ✓ Visual Explorer returns to starting state"
echo ""
echo "  Full pre-flight checklist: ./howdoirun.sh"
echo ""
echo "╔══════════════════════════════════════════════════════════════════════════╗"
echo "║  End of demo flow. Good luck! 🚀                                        ║"
echo "╚══════════════════════════════════════════════════════════════════════════╝"
echo ""
