#!/usr/bin/env bash
# setup_infra.sh
#
# Provisions the Summit Demo infrastructure on AWS via Terraform:
#   - Report server: nginx HTTPS, serves the AAP-generated failover report
#   - MCP server: NetBox read-only MCP server accessed via SSH stdio
#
# Then registers both VMs with AAP (Machine credential + report server host).
#
# Prerequisites:
#   1. Authenticate to AWS first:
#        assume --region eu-west-2
#   2. Run ./setup.sh (creates .env)
#   3. Run: uv run --with requests python setup_aap.py (configures AAP)
#
# Usage: ./setup_infra.sh

set -euo pipefail

# ── Check AWS credentials are available ───────────────────────────────────────
if ! aws sts get-caller-identity --region eu-west-2 &>/dev/null; then
  echo ""
  echo "ERROR: No valid AWS credentials found."
  echo ""
  echo "  Run this first:  assume --region eu-west-2"
  echo ""
  exit 1
fi

AWS_ACCOUNT=$(aws sts get-caller-identity --region eu-west-2 --query Account --output text)
echo "AWS credentials OK (account: $AWS_ACCOUNT, region: eu-west-2)"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/infra"
KEYS_DIR="$INFRA_DIR/keys"

# Load credentials
if [ ! -f "$SCRIPT_DIR/.env" ]; then
  echo "ERROR: .env not found. Run ./setup.sh first."
  exit 1
fi
set -a; source "$SCRIPT_DIR/.env"; set +a

echo "========================================================"
echo "  Step 1: Terraform — provision VMs"
echo "========================================================"

cd "$INFRA_DIR"
terraform init -upgrade -input=false

# Pass the NetBox token to Terraform so the MCP VM can be configured
terraform apply -auto-approve -input=false \
  -var="aws_region=eu-west-2" \
  -var="netbox_url=${NETBOX_URL}" \
  -var="netbox_token=${NETBOX_TOKEN}"

# Capture outputs
REPORT_IP=$(terraform output -raw report_server_ip)
MCP_IP=$(terraform output -raw mcp_server_ip)
SSH_PORT=$(terraform output -raw ssh_port)
PRIVATE_KEY_PATH=$(realpath "$KEYS_DIR/summit-demo.pem")
REPORT_URL=$(terraform output -raw report_url)

echo ""
echo "  Report server:  $REPORT_IP  ($REPORT_URL)"
echo "  MCP server:     $MCP_IP"
echo "  SSH port:       $SSH_PORT"
echo "  Private key:    $PRIVATE_KEY_PATH"

cd "$SCRIPT_DIR"

echo ""
echo "========================================================"
echo "  Step 2: Wait for SSH on both VMs"
echo "========================================================"

wait_for_ssh() {
  local ip=$1
  local label=$2
  echo -n "  Waiting for SSH on $label ($ip:$SSH_PORT)..."
  for i in $(seq 1 48); do
    if ssh -o StrictHostKeyChecking=no \
           -o ConnectTimeout=5 \
           -o BatchMode=yes \
           -i "$PRIVATE_KEY_PATH" \
           -p "$SSH_PORT" \
           "ec2-user@$ip" "echo ok" &>/dev/null; then
      echo " ready."
      return 0
    fi
    echo -n "."
    sleep 5
  done
  echo " TIMEOUT (VM may still be initialising — check manually)"
}

wait_for_ssh "$REPORT_IP" "report-server"
wait_for_ssh "$MCP_IP" "mcp-server"

echo ""
echo "========================================================"
echo "  Step 3: Write infra vars for Ansible"
echo "========================================================"

cat > "$SCRIPT_DIR/ansible/vars/infra.yml" << VARSEOF
---
# Generated by setup_infra.sh — do not commit (gitignored)
report_server_host: "$REPORT_IP"
report_server_port: $SSH_PORT
report_server_user: "ec2-user"
report_server_path: "/var/www/html/failover_report.html"
report_url: "$REPORT_URL"
VARSEOF

echo "  Written: ansible/vars/infra.yml"

echo ""
echo "========================================================"
echo "  Step 4: Register report server with AAP"
echo "========================================================"

uv run --with requests python setup_aap.py \
  --report-server-ip "$REPORT_IP" \
  --report-server-port "$SSH_PORT" \
  --private-key-path "$PRIVATE_KEY_PATH"

echo ""
echo "========================================================"
echo "  Done!"
echo "========================================================"

MCP_CMD=$(terraform -chdir="$INFRA_DIR" output -raw mcp_claude_add_command 2>/dev/null || echo "")

cat << SUMMARY

  ┌─────────────────────────────────────────────────────────────┐
  │  Infrastructure Ready                                       │
  ├─────────────────────────────────────────────────────────────┤
  │  Report server                                              │
  │    URL:  $REPORT_URL
  │    SSH:  ssh -i infra/keys/summit-demo.pem -p $SSH_PORT ec2-user@$REPORT_IP
  │                                                             │
  │  MCP server                                                 │
  │    SSH:  ssh -i infra/keys/summit-demo.pem -p $SSH_PORT ec2-user@$MCP_IP
  └─────────────────────────────────────────────────────────────┘

  To register the NetBox MCP server with Claude Code, run:

  claude mcp add netbox-mcp \\
    -e NETBOX_URL=${NETBOX_URL} \\
    -e NETBOX_TOKEN=${NETBOX_TOKEN} \\
    -e VERIFY_SSL=true \\
    -- ssh -o StrictHostKeyChecking=no \\
           -i $PRIVATE_KEY_PATH \\
           -p $SSH_PORT \\
           ec2-user@$MCP_IP \\
           /home/ec2-user/netbox-mcp/.venv/bin/netbox-mcp-server

  Then restart Claude Code and verify with: claude mcp list

  To tear down all infrastructure: cd infra && terraform destroy
SUMMARY
