#!/usr/bin/env bash
# setup_infra.sh
#
# Provisions the Summit Demo report server on AWS via Terraform, then
# registers it with AAP (Machine credential + host in inventory).
#
# Assumes:
#   - AWS credentials are already configured (env vars or ~/.aws)
#   - .env exists (run ./setup.sh first)
#   - AAP is already configured (run: uv run --with requests python setup_aap.py first)
#
# Usage: ./setup_infra.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/infra"
KEYS_DIR="$INFRA_DIR/keys"

# Load credentials
if [ ! -f "$SCRIPT_DIR/.env" ]; then
  echo "ERROR: .env not found. Run ./setup.sh first."
  exit 1
fi
set -a; source "$SCRIPT_DIR/.env"; set +a

echo "========================================================"
echo "  Step 1: Terraform — provision report server"
echo "========================================================"

cd "$INFRA_DIR"
terraform init -upgrade -input=false

terraform apply -auto-approve -input=false

# Capture outputs
PUBLIC_IP=$(terraform output -raw public_ip)
SSH_PORT=$(terraform output -raw ssh_port)
PRIVATE_KEY_PATH=$(realpath "$KEYS_DIR/summit-demo.pem")
REPORT_URL=$(terraform output -raw report_url)

echo ""
echo "  Public IP:    $PUBLIC_IP"
echo "  SSH port:     $SSH_PORT"
echo "  Report URL:   $REPORT_URL"
echo "  Private key:  $PRIVATE_KEY_PATH"

cd "$SCRIPT_DIR"

echo ""
echo "========================================================"
echo "  Step 2: Wait for SSH to become available"
echo "========================================================"

echo -n "  Waiting for SSH on $PUBLIC_IP:$SSH_PORT..."
for i in $(seq 1 40); do
  if ssh -o StrictHostKeyChecking=no \
         -o ConnectTimeout=5 \
         -o BatchMode=yes \
         -i "$PRIVATE_KEY_PATH" \
         -p "$SSH_PORT" \
         "ec2-user@$PUBLIC_IP" \
         "echo ok" &>/dev/null; then
    echo " ready."
    break
  fi
  echo -n "."
  sleep 5
done

echo ""
echo "========================================================"
echo "  Step 3: Write infra vars for Ansible"
echo "========================================================"

cat > "$SCRIPT_DIR/ansible/vars/infra.yml" << VARSEOF
---
# Generated by setup_infra.sh — do not commit
report_server_host: "$PUBLIC_IP"
report_server_port: $SSH_PORT
report_server_user: "ec2-user"
report_server_path: "/var/www/html/failover_report.html"
report_url: "$REPORT_URL"
VARSEOF

echo "  Written: ansible/vars/infra.yml"

echo ""
echo "========================================================"
echo "  Step 4: Register with AAP"
echo "========================================================"

uv run --with requests python setup_aap.py \
  --report-server-ip "$PUBLIC_IP" \
  --report-server-port "$SSH_PORT" \
  --private-key-path "$PRIVATE_KEY_PATH"

echo ""
echo "========================================================"
echo "  Done!"
echo "========================================================"
echo ""
echo "  Report server:  $REPORT_URL"
echo "  SSH access:     ssh -i infra/keys/summit-demo.pem -p $SSH_PORT ec2-user@$PUBLIC_IP"
echo ""
echo "  To tear down:   cd infra && terraform destroy"
