variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "eu-west-3"  # Paris
}

variable "ssh_port" {
  description = "Non-standard SSH port (used on all VMs)"
  type        = number
  default     = 2222
}

variable "instance_type" {
  description = "EC2 instance type for the report server"
  type        = string
  default     = "t3.micro"
}

variable "mcp_instance_type" {
  description = "EC2 instance type for the MCP server"
  type        = string
  default     = "t3.micro"
}

variable "key_name" {
  description = "AWS EC2 key pair name"
  type        = string
  default     = "summit-demo-2026"
}

variable "netbox_url" {
  description = "NetBox instance URL for the MCP server"
  type        = string
  # Passed in by setup_infra.sh from .env — no default to avoid committing instance URLs
}

variable "netbox_token" {
  description = "NetBox API token for the MCP server (read-only)"
  type        = string
  sensitive   = true
  # Passed in by setup_infra.sh from .env — never hardcode here
}

variable "router_instance_type" {
  description = "EC2 instance type for the Cisco router (minimum c5n.large for IOS-XE)"
  type        = string
  default     = "c5n.large"
}

variable "router_password" {
  description = "Password for the local IOS user (iosuser) on the Cisco demo router — generated by setup_infra.sh"
  type        = string
  sensitive   = true
  # No default — must be supplied by setup_infra.sh so a fresh password is generated each provisioning run
}
